---
title: "Forward Stepwise Selection + Logistic Regression"
output: html_notebook
---

```{r}
# Creating Training data dataframe
library(plyr)
library(dplyr)
dexter_train <- read.delim("~/R/dexter_train.data", header=FALSE)
d <- data.frame(dexter_train)
train_df <- data.frame(matrix(0,ncol = 20000, nrow = 300))
cols = c(1:20000)
colnames(train_df) = cols
```

```{r}
for (i in c(1:300)){
  x<-d %>% slice(i)
  x<-paste(unlist(x),collapse = " ")
  x<-unlist(strsplit(x," "))
  for (val in x){
    val<- unlist(strsplit(val,":"))
    train_df[i,val[1]] = val[2]
  }
}
train_df <- as.data.frame(sapply(train_df, as.numeric))
```

```{r}
head(train_df)
```

```{r}
dexter_train_labels <- read.table("~/R/dexter_train.labels", quote="\"", comment.char="")
dt1 <- data.frame(dexter_train_labels)
dt1<-as.numeric(unlist(dt1))
dt1
```

```{r}
#Validation data dataframe
dexter_val <- read.delim("~/R/dexter_valid.data", header=FALSE)
dval <- data.frame(dexter_val)
val_df <- data.frame(matrix(0,ncol = 20000, nrow = 300))
cols = c(1:20000)
colnames(val_df) = cols
```


```{r}
for (i in c(1:300)){
  x<-dval %>% slice(i)
  x<-paste(unlist(x),collapse = " ")
  x<-unlist(strsplit(x," "))
  for (val in x){
    val<- unlist(strsplit(val,":"))
    val_df[i,val[1]] = val[2]
  }
}
val_df <- as.data.frame(sapply(val_df, as.numeric))
```

```{r}
dexter_val_labels <- read.table("~/R/dexter_valid.labels", quote="\"", comment.char="")
dt2 <- data.frame(dexter_val_labels)
dt2<-as.numeric(unlist(dt2))
```

```{r}
library(aod)
library(ggplot2)
```

```{r}
# Perform lasso regression for feature selection and prune the features
library(glmnet)

grid = 10^seq(10,-2,length=100)
lasso.mod = glmnet(train_df, dt1, alpha=1, lambda = grid)
cv.out = cv.glmnet(as.matrix(train_df),dt1,alpha=1)
selected_features = c(which(!coef(cv.out, s = "lambda.min")==0))
train_df = train_df[selected_features]
```

```{r}
# Forward stepwise selection
#define intercept-only model
intercept_only <- lm(dexter_train_labels ~ 1, data=train_df)

#define model with all predictors
all <- lm(dexter_train_labels~ ., data=train_df)

forward <- step(intercept_only, direction='forward', scope=formula(all), trace=0)
forward$anova
```

```{r}
forward$coefficients
```


```{r}
#perform backward stepwise regression
backward <- step(all, direction='backward', scope=formula(all), trace=0)

#view results of backward stepwise regression
backward$anova
```

